### PR TITLE
Feature/add logout

### PR DESCRIPTION
**Pull request by jupiter007**
## Description

Fixes # [#65](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/65)

1. Added a "logout" link and API endpoint to delete the "dmspt" cookie when the user logs out.
2. Added an AuthProvider to wrap around the content so that we can share the authentication state in the client components, and update when the user logs in or logs out.
3. Since I added an AuthProvider, I had to create a custom render function for the unit tests of client components that use the AuthProvider.

Eventually, we should also be calling the backend server so that the JWT token can be invalidated.

## Type of change
Please delete options that are not relevant

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

1. Start the app
4. Go to http://localhost:3000/login and log in
5. Notice the "dmspt" cookie after you log in
6. Notice that the link text in the header says "Log out" after you successfully log in
8. Click on the "Log out" link in the header
9. You should be redirected to the "/login" page and the cookie should've deleted
10. Notice that the link text in the header now says "Log in" after you successfully logged out.
11. Notice that the "dmspt" cookie has been deleted.

## Checklist:
- [] My code follows the style guidelines of this project (Not a final design. I just inserted a link into the header for testing purposes.)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I updated the CHANGELOG.md and added documentation if necessary
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have completed manual or automated accessibility testing for my changes
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by briri — APPROVED** [review]
This looks good to me Juliet

**Comment by jupiter007** [comment]
@briri I made an update to use a context wrapper around the content, so that the client components can easily grab the authentication state, and update it when the user logs out or logs in.

**Review by briri — APPROVED** [review]
Thanks @jupiter007 I think this will be a good way to handle the auth state. the AuthContext also seems like a good spot to add an `isAdmin` state or something similar when we get around to permissions

**Comment by jupiter007** [comment]
> Thanks @jupiter007 I think this will be a good way to handle the auth state. the AuthContext also seems like a good spot to add an `isAdmin` state or something similar when we get around to permissions

Yes. Also hoping to use middleware to control routing for different roles.

**Pull request merged**
