### PR TITLE
(#80) Added the custom SVG Icons and Component

### LINKED ISSUE #80: Decide and integrate on a Icon set or Library (FontAwesome or Google Material)
We need to pick an icon library to use.

We could use FontAwesome since it's popular. They do have some limitations when
using the non-paid icons, however.

Google’s material icons is another option. Not as expansive as the **paid**
FontAwesome set. It does have a good range of symbols and icons available for
free. Another benefit of this set is that it is consistent with other
Google products, and Android phones.

[1] - https://fontawesome.com/
[2] - https://fonts.google.com/icons

### PR DESCRIPTION
**Pull request by andrewebdev**
## Description

Changed from font-based icons to self-managed SVG icons.

Fixes #80

## How Has This Been Tested?
Tested on the styleguide in the "Icons" section, as well as the ReMirror Editor.

### CODE REVIEW

**Comment by andrewebdev** [comment]
@jupiter007 & @briri While working on this I noticed that, in `layout.tsx` we are importing font-awesome css. It looks like font-awesome is a dependency of the project. It this something that is still required, or is it something that should be removed? My assumption is that it's left-over from previous iterations of testing/prototyping.

**Comment by briri** [comment]
@jupiter007 was Fontawesome just copied over from phase 1 and used as a placeholder?

**Comment by jupiter007** [comment]
@andrewebdev and @briri , yes it is currently just a placeholder.

**Review by jupiter007 — DISMISSED** [review]

**Comment by jupiter007** [comment]
@andrewebdev  One minor thing I noticed is that there are a couple of errors in the components/Editor/index.tsx file. Since we're not using that Editor yet, we could hold off and update it later. The errors are:
- '"@remirror/core-utils"' has no exported member named 'EditorState'. Did you mean 'isEditorState'?
- "Object literal may only specify known properties, and 'text' does not exist in type 'OmitTextAndPosition<Annotation>" on line 55.

**Comment by jupiter007** [comment]
> @andrewebdev One minor thing I noticed is that there are a couple of errors in the components/Editor/index.tsx file. Since we're not using that Editor yet, we could hold off and update it later. The errors are:
> 
> * '"@remirror/core-utils"' has no exported member named 'EditorState'. Did you mean 'isEditorState'?
> * "Object literal may only specify known properties, and 'text' does not exist in type 'OmitTextAndPosition" on line 55.

Actually, we should go ahead and fix that first error with "isEditorState".

**Comment by jupiter007** [comment]
Hi @andrewebdev. I fixed the issue with "Editor/index.ts"  in the feature branch I am working on so I'll go ahead and approve this PR so you can merge.

The fix was I imported "EditorState" from another remirror library:
```
import {
  EditorState,
} from '@remirror/pm/state';
```

We were seeing a 500 error when we loaded the styleguide page because there is an issue with Remirror in NextJS where the server rendering doesn't work too nicely with it.  So to get around it, I waited until the component was mounted before proceeding:

```
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    setIsMounted(true)
  }, [])
  if (!isMounted) {
    return null; // or a loading indicator
  }
```

**Review by jupiter007 — APPROVED** [review]

**Comment by andrewebdev** [comment]
Hi @jupiter007 just wondering if this is okay to be merged into development? I want to start work on the next couple of tasks and would be nice to get this merged so that I can rebase my other branches off the changes. ;)

**Comment by jupiter007** [comment]
> Hi @jupiter007 just wondering if this is okay to be merged into development? I want to start work on the next couple of tasks and would be nice to get this merged so that I can rebase my other branches off the changes. ;)

Yes you can merge @andrewebdev

**Pull request merged**
